[workspace]
resolver="2"

members = [
    "wgpu_main"
]

[profile.release]
debug = false
lto = true
strip = true
panic = "abort"
codegen-units=1
opt-level="s"

[profile.production]
inherits="release"
opt-level=3
incremental=false
panic="abort"
